name: smart_care_v2
description: AES.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter
    
  clipboard: ^0.1.3
  flutter_animate: ^4.1.1+1
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.3+1
  lottie: ^2.3.2
  password_strength: ^0.2.0
  url_launcher: ^6.1.10
  patterns_canvas: ^0.4.0
  cached_network_image: ^3.2.3
  fl_chart: ^0.62.0
  username: ^0.2.3
  flutter_profile_picture: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/pictures/
    - assets/lotties/
    